export const GET_PRODUCTS_NAME = "GET_PRODUCTS_NAME";
export const GET_PRODUCTS_BY_PRICE = "GET_PRODUCTS_BY_PRICE";
export const GET_PRODUCTS_BY_CONDITION = "GET_PRODUCTS_BY_CONDITION";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_CATEGORY = "GET_CATEGORY";
export const GET_PRODUCTS_CAT_BY_CONDITION = "GET_PRODUCTS_CAT_BY_CONDITION";
export const GET_PRODUCTS_CAT_BY_PRICE = "GET_PRODUCTS_CAT_BY_PRICE";
export const GET_FILTERS = "GET_FILTERS"

export const GET_CAT_FILTERS = "GET_CAT_FILTERS";
export const GET_CATEGORY = "GET_CATEGORY";
export const GET_FILTERS = "GET_FILTERS"
