export const GET_PRODUCTS_NAME = "GET_PRODUCTS_NAME";
export const GET_PRODUCTS_BY_PRICE = "GET_PRODUCTS_BY_PRICE";
export const GET_PRODUCTS_BY_CONDITION = "GET_PRODUCTS_BY_CONDITION";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_PRODUCT = "GET_PRODUCT";